POST http://localhost:3000/v1/login
Content-Type : application/json

{
  "email": "bennis.salim@gmail.com",
  "password": "0000"
}
###
POST http://localhost:3000/v1/signup
Content-Type : application/json

{
  "email": "test2@email.com",
  "lastname": "toto",
  "firstname": "titi",
  "password": "0000",
  "passwordConfirm": "0000"
}